import { createServerClient } from '@supabase/ssr'
import { createClient as createServiceClient } from '@supabase/supabase-js'
import { NextResponse, type NextRequest } from 'next/server'
import { cookies } from 'next/headers'
import { sendInviteEmail } from '@/lib/email'

export async function POST(request: NextRequest) {
  // Auth check — must be clinic_admin
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll(s) { s.forEach(({ name, value, options }) => cookieStore.set(name, value, options)) },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised.' }, { status: 401 })

  const { data: cu } = await supabase
    .from('clinic_users').select('role').eq('user_id', user.id).single()
  if (!cu || !['clinic_admin', 'platform_owner'].includes(cu.role)) {
    return NextResponse.json({ error: 'Forbidden.' }, { status: 403 })
  }

  let body: { clinic_id?: string; email?: string; role?: string }
  try { body = await request.json() } catch {
    return NextResponse.json({ error: 'Invalid request.' }, { status: 400 })
  }

  const { clinic_id, email, role = 'clinic_admin' } = body

  if (!clinic_id || !email?.trim()) {
    return NextResponse.json({ error: 'clinic_id and email are required.' }, { status: 400 })
  }

  if (!['clinic_admin', 'staff'].includes(role)) {
    return NextResponse.json({ error: 'Invalid role.' }, { status: 400 })
  }

  const service = createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )

  // Check clinic exists
  const { data: clinic } = await service.from('clinics').select('id, name').eq('id', clinic_id).single()
  if (!clinic) return NextResponse.json({ error: 'Clinic not found.' }, { status: 404 })

  // Check for an existing pending invite for this email+clinic
  const { data: existingInvite } = await service
    .from('clinic_invites')
    .select('id, expires_at, accepted_at')
    .eq('clinic_id', clinic_id)
    .eq('email', email.trim())
    .is('accepted_at', null)
    .single()

  if (existingInvite && new Date(existingInvite.expires_at) > new Date()) {
    return NextResponse.json(
      { error: 'An active invite already exists for this email. Copy the invite link from the history.' },
      { status: 409 }
    )
  }

  // Create invite (token auto-generated by DB default)
  const { data: invite, error: inviteError } = await service
    .from('clinic_invites')
    .insert({
      clinic_id,
      email: email.trim(),
      role,
      invited_by: user.email ?? user.id,
    })
    .select('token')
    .single()

  if (inviteError || !invite) {
    console.error('[admin/invite] insert error:', inviteError)
    return NextResponse.json({ error: 'Failed to create invite.' }, { status: 500 })
  }

  // Send branded invite email
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://app.clinicforce.io'
  const inviteUrl = `${siteUrl}/invite/${invite.token}`

  try {
    await sendInviteEmail({
      to:         email.trim(),
      clinicName: clinic.name,
      inviteUrl,
      invitedBy:  user.email ?? 'Your admin',
      role,
    })
  } catch (emailErr) {
    // Log but don't fail — invite token is still valid, admin can copy link
    console.error('[admin/invite] email send failed:', emailErr)
    return NextResponse.json({
      success: true,
      token: invite.token,
      emailSent: false,
      warning: 'Invite created but email could not be sent. Copy the link to share manually.',
    })
  }

  return NextResponse.json({ success: true, token: invite.token, emailSent: true })
}
